import 'dart:async';
import 'dart:io';

class Reporter {
  final bool verbose;
  final bool useColor;

  Reporter({required this.verbose}) : useColor = stdout.hasTerminal;

  String _color(String code, String text) =>
      useColor ? '$code$text\u001b[0m' : text;

  Future<void> generateReport(List diagnostics, dynamic detector, int score,
      int errors, int warnings, int deadCode, int fileCount) async {
    _printCommand();
    _printProjectDetection(detector);
    await _printHeader();
    _printLintDiagnostics(diagnostics);
    _printDeadCodeDiagnostics(diagnostics);
    _printHealthScore(score, errors, warnings, deadCode, fileCount);
    _printPriorityFixes(diagnostics);
    _printFooter();
  }

  Future<void> generateMarkdownReport({
    required String projectPath,
    required List diagnostics,
    required dynamic detector,
    required int score,
    required int errors,
    required int warnings,
    required int deadCode,
    required int fileCount,
  }) async {
    final buffer = StringBuffer();
    final now = DateTime.now();
    final dateStr =
        '${now.year}-${now.month.toString().padLeft(2, '0')}-${now.day.toString().padLeft(2, '0')}';

    final label = score >= 75
        ? 'Great'
        : score >= 50
            ? 'Needs work'
            : 'Critical';

    // Header
    buffer.writeln('# Flutter Doctor Report');
    buffer.writeln();
    buffer.writeln(
        '> Generated by [flutter_doctor](https://github.com/yourname/flutter_doctor) on $dateStr');
    buffer.writeln();

    // Score summary
    buffer.writeln('## Health Score: $score / 100 — $label');
    buffer.writeln();
    buffer.writeln('| Metric | Count |');
    buffer.writeln('|--------|-------|');
    buffer.writeln('| Errors | $errors |');
    buffer.writeln('| Warnings | $warnings |');
    buffer.writeln('| Dead code | $deadCode |');
    buffer.writeln('| Files scanned | $fileCount |');
    buffer.writeln('| Flutter version | ${detector.flutterVersion} |');
    buffer.writeln('| Dart version | ${detector.dartVersion} |');
    if ((detector.stateManagement as String).isNotEmpty) {
      buffer.writeln('| State management | ${detector.stateManagement} |');
    }
    buffer.writeln();

    // Lint errors
    final errs = diagnostics.where((d) => d['type'] == 'ERR').toList();
    if (errs.isNotEmpty) {
      buffer.writeln('## Errors (must fix)');
      buffer.writeln();
      buffer.writeln('| Rule | Location | Description |');
      buffer.writeln('|------|----------|-------------|');
      for (final d in errs) {
        final rule = d['rule'] ?? '';
        final location = d['location'] ?? '';
        final desc = d['description'] ?? '';
        buffer.writeln('| `$rule` | `$location` | $desc |');
      }
      buffer.writeln();
    }

    // Lint warnings
    final warns = diagnostics.where((d) => d['type'] == 'WARN').toList();
    if (warns.isNotEmpty) {
      buffer.writeln('## Warnings (should fix)');
      buffer.writeln();
      buffer.writeln('| Rule | Location | Description |');
      buffer.writeln('|------|----------|-------------|');
      for (final d in warns) {
        final rule = d['rule'] ?? '';
        final location = d['location'] ?? '';
        final desc = d['description'] ?? '';
        buffer.writeln('| `$rule` | `$location` | $desc |');
      }
      buffer.writeln();
    }

    // Dead code
    final deads = diagnostics.where((d) => d['type'] == 'DEAD').toList();
    if (deads.isNotEmpty) {
      buffer.writeln('## Dead Code (clean up)');
      buffer.writeln();
      buffer.writeln('| Type | Item |');
      buffer.writeln('|------|------|');
      for (final d in deads) {
        final subType = d['subType'] ?? 'UNKNOWN';
        final desc = d['description'] ?? '';
        buffer.writeln('| $subType | `$desc` |');
      }
      buffer.writeln();
    }

    // ── Priority Fixes for AI Agent ──────────────────
    buffer.writeln('## Priority Fixes for AI Agent');
    buffer.writeln();
    buffer.writeln('> Read this file and fix all issues below in order.');
    buffer.writeln('> Fix errors first, then warnings, then improvements.');
    buffer.writeln();

    // ── ERRORS ────────────────────────────────────────
    if (errs.isNotEmpty) {
      buffer.writeln('---');
      buffer.writeln();
      buffer.writeln(
          '### 🔴 ERRORS — Fix these first (each causes crashes or memory leaks)');
      buffer.writeln();
      for (final d in errs) {
        final rule = d['rule'] ?? '';
        final location = d['location'] ?? '';
        final desc = d['description'] ?? '';
        buffer.writeln('#### `$rule`');
        buffer.writeln('- **File:** `$location`');
        buffer.writeln('- **Problem:** $desc');
        buffer.writeln('- **Why this is critical:** ${_errorExplanation(rule)}');
        buffer.writeln('- **How to fix:** ${_errorFix(rule)}');
        buffer.writeln();
      }
    }

    // ── WARNINGS ─────────────────────────────────────
    if (warns.isNotEmpty) {
      buffer.writeln('---');
      buffer.writeln();
      buffer.writeln(
          '### 🟡 WARNINGS — Fix after errors (performance and correctness issues)');
      buffer.writeln();
      for (final d in warns) {
        final rule = d['rule'] ?? '';
        final location = d['location'] ?? '';
        final desc = d['description'] ?? '';
        buffer.writeln('#### `$rule`');
        buffer.writeln('- **File:** `$location`');
        buffer.writeln('- **Problem:** $desc');
        buffer.writeln('- **Why this matters:** ${_warningExplanation(rule)}');
        buffer.writeln('- **How to fix:** ${_warningFix(rule)}');
        buffer.writeln();
      }
    }

    // ── DEAD CODE ─────────────────────────────────────
    if (deads.isNotEmpty) {
      buffer.writeln('---');
      buffer.writeln();
      buffer.writeln('### 🔵 DEAD CODE — Clean up (removes bloat and confusion)');
      buffer.writeln();
      for (final d in deads) {
        final subType = d['subType'] ?? 'UNKNOWN';
        final desc = d['description'] ?? '';
        buffer.writeln('#### $subType: `$desc`');
        buffer.writeln('- **Action:** ${_deadCodeFix(subType)}');
        buffer.writeln();
      }
    }

    // ── IMPROVEMENTS ──────────────────────────────────
    buffer.writeln('---');
    buffer.writeln();
    buffer.writeln('### 🟢 IMPROVEMENTS — Do after all fixes');
    buffer.writeln();
    buffer.writeln('After fixing all errors and warnings above:');
    buffer.writeln();
    buffer.writeln('1. Run `flutter analyze` to confirm 0 issues remain');
    buffer.writeln('2. Run `flutter test` to confirm no regressions');
    buffer.writeln(
        '3. Run `flutter_doctor . --verbose` to regenerate this report');
    buffer.writeln('4. Target score: **75 or above** to pass CI gate');
    buffer.writeln();

    if (score < 50) {
      buffer.writeln('> ⚠️ Score is **Critical ($score/100)**.');
      buffer.writeln(
          '> Start with errors only. Do not touch warnings until all errors are fixed.');
    } else if (score < 75) {
      buffer.writeln('> ⚠️ Score is **Needs work ($score/100)**.');
      buffer.writeln(
          '> Fix warnings grouped by file to minimize context switching.');
    } else {
      buffer.writeln(
          '> ✅ Score is **Great ($score/100)**. Only minor cleanup needed.');
    }
    buffer.writeln();

    // Footer
    buffer.writeln('---');
    buffer.writeln(
        '_Generated by `flutter_doctor` · Run `flutter_doctor . --verbose` to refresh_');

    // Write file
    final outputFile = File('$projectPath/NEEDEDFIX.md');
    await outputFile.writeAsString(buffer.toString());
  }

  String _errorExplanation(String rule) {
    switch (rule) {
      case 'flutter/no-build-context-async':
        return 'Using BuildContext after an await means the widget may have been '
            'unmounted by the time the context is accessed. This causes '
            '"Looking up a deactivated widget\'s ancestor is unsafe" crashes at runtime.';
      case 'flutter/dispose-controllers':
        return 'AnimationController and other controllers hold resources and '
            'listeners. Not disposing them causes memory leaks that accumulate '
            'every time the widget is rebuilt or navigated to.';
      case 'dart/unclosed-stream':
        return 'A StreamSubscription that is never cancelled keeps listening '
            'forever even after the widget is gone. This causes memory leaks '
            'and can trigger setState() on unmounted widgets.';
      case 'dart/nullable-without-check':
        return 'Accessing a nullable value without a null check will throw a '
            'Null check operator used on a null value exception at runtime, '
            'crashing the app.';
      case 'flutter/setstate-after-dispose':
        return 'Calling setState() after dispose() throws "setState() called '
            'after dispose()" and crashes the app. Always check mounted first.';
      case 'flutter/initstate-without-mounted':
        return 'Calling async operations in initState without checking mounted '
            'before using context or setState can cause crashes after the '
            'widget is removed from the tree.';
      case 'flutter/provider-outside-tree':
        return 'Provider.of() called outside the widget build() method cannot '
            'find the provider in the widget tree and throws a ProviderNotFoundException.';
      default:
        return 'This error causes runtime crashes or undefined behavior. '
            'Fix immediately before other changes.';
    }
  }

  String _errorFix(String rule) {
    switch (rule) {
      case 'flutter/no-build-context-async':
        return 'Check `if (!mounted) return;` immediately after every `await`. '
            'Store any values you need from context BEFORE the await, not after. '
            'Example: `final nav = Navigator.of(context); await something(); nav.push(...);`';
      case 'flutter/dispose-controllers':
        return 'Override `dispose()` in the State class and call `controller.dispose()` '
            'for every AnimationController, TextEditingController, ScrollController, '
            'TabController, and PageController created in this widget.';
      case 'dart/unclosed-stream':
        return 'Store the StreamSubscription in a field: '
            '`StreamSubscription? _sub;` then in `dispose()` call `_sub?.cancel();`. '
            'Never call `.listen()` without saving the return value.';
      case 'dart/nullable-without-check':
        return 'Use null-aware operators: `?.` for method calls, `??` for fallback '
            'values, or add an explicit `if (value == null) return;` guard before use. '
            'Avoid using `!` unless you are 100% certain the value is non-null.';
      case 'flutter/setstate-after-dispose':
        return 'Wrap every setState call with `if (!mounted) return;` before it. '
            'For async operations: `await something(); if (!mounted) return; setState(() {});`';
      case 'flutter/initstate-without-mounted':
        return 'In initState, after any await add: `if (!mounted) return;` '
            'before using context or calling setState.';
      case 'flutter/provider-outside-tree':
        return 'Move Provider.of() calls inside the build() method. '
            'If needed outside build, use a callback or pass the value as a parameter.';
      default:
        return 'Read the error message at the file location and apply the '
            'recommended fix from the dart analyzer message.';
    }
  }

  String _warningExplanation(String rule) {
    switch (rule) {
      case 'flutter/missing-const':
        return 'Without const, Flutter rebuilds this widget every time the '
            'parent rebuilds even if nothing changed. Const widgets are cached '
            'and reused, significantly improving render performance.';
      case 'flutter/list-view-shrink-wrap':
        return 'shrinkWrap: true forces ListView to calculate its full height '
            'by rendering ALL items at once even off-screen. In a large list '
            'this causes severe jank and defeats the purpose of lazy loading.';
      case 'flutter/hardcoded-string':
        return 'Hardcoded strings cannot be translated for international users '
            'and are harder to maintain. All user-visible text should use '
            'AppLocalizations or a constants file.';
      case 'flutter/missing-semantics':
        return 'Icon widgets without semanticLabel are invisible to screen '
            'readers, making the app inaccessible to visually impaired users '
            'and failing accessibility audits.';
      case 'flutter/image-cache-miss':
        return 'Image.network without cacheWidth loads the full resolution image '
            'into memory regardless of display size. In lists with many images '
            'this causes out-of-memory crashes on low-end devices.';
      case 'flutter/rebuild-on-provider':
        return 'Expensive computation inside build() runs on every rebuild. '
            'If a parent widget rebuilds frequently this creates visible '
            'performance drops and dropped frames.';
      case 'deprecated_member_use':
        return 'Using deprecated APIs means the code will break in a future '
            'Flutter/Dart version when the API is removed.';
      case 'unused_import':
        return 'Unused imports increase compile time and create confusion '
            'about what the file actually depends on.';
      case 'unused_catch_stack':
        return 'Catching a stack trace that is never used wastes memory '
            'and suggests the error handling is incomplete.';
      default:
        return 'This warning degrades performance, maintainability, or '
            'accessibility. Fix to improve overall code quality.';
    }
  }

  String _warningFix(String rule) {
    switch (rule) {
      case 'flutter/missing-const':
        return 'Add `const` keyword before the widget constructor. '
            'Example: `const Text("hello")` instead of `Text("hello")`. '
            'If the widget has dynamic children it cannot be const — skip those.';
      case 'flutter/list-view-shrink-wrap':
        return 'Replace `shrinkWrap: true` with a `SliverList` inside a '
            '`CustomScrollView`, or wrap the ListView in an `Expanded` or '
            '`SizedBox` with a fixed height to give it bounded constraints.';
      case 'flutter/hardcoded-string':
        return 'Move the string to `lib/l10n/` using Flutter\'s intl package, '
            'or at minimum to a `AppStrings` constants class. '
            'Replace the literal with the constant reference.';
      case 'flutter/missing-semantics':
        return 'Add `semanticLabel` parameter to Icon: '
            '`Icon(Icons.close, semanticLabel: "Close dialog")`. '
            'If the icon is purely decorative use `ExcludeSemantics` wrapper.';
      case 'flutter/image-cache-miss':
        return 'Add `cacheWidth` matching the display size in logical pixels: '
            '`Image.network(url, cacheWidth: 200)`. '
            'Use `MediaQuery.of(context).devicePixelRatio` to calculate '
            'the right pixel size for the screen density.';
      case 'flutter/rebuild-on-provider':
        return 'Move expensive calculations outside build() into a variable '
            'computed in initState or into the provider/bloc itself. '
            'Use `select()` on Riverpod/Provider to limit rebuilds to only '
            'the specific value that changed.';
      case 'deprecated_member_use':
        return 'Check the deprecation message for the replacement API. '
            'For `withOpacity` use `.withValues(alpha: x)` in Flutter 3.x+. '
            'Search the Flutter migration guides for the specific API.';
      case 'unused_import':
        return 'Delete the import line entirely. '
            'In VS Code press Ctrl+Shift+P → "Organize Imports" to remove all at once.';
      case 'unused_catch_stack':
        return 'Either use the stack trace in your error logging: '
            '`} catch (e, stack) { log(e.toString(), stackTrace: stack); }` '
            'or remove the stack parameter: `} catch (e) {`';
      default:
        return 'Read the warning at the file location and apply the '
            'recommended fix from the dart analyzer message.';
    }
  }

  String _deadCodeFix(String subType) {
    switch (subType.trim().toUpperCase()) {
      case 'UNUSED FILE':
        return 'Verify this file is truly unused by searching for its import '
            'across the project. If confirmed unused, delete the file. '
            'Do not delete if it is a route, entry point, or platform file.';
      case 'UNUSED EXPORT':
        return 'Remove the unused function or class export. If it is part of '
            'a public API that might be used externally, keep it but add a comment.';
      case 'DUPLICATE':
        return 'Compare the two files. Pick the better one and update all '
            'imports across the project to use only that one. Delete the other.';
      default:
        return 'Review this dead code item and remove it if it is safe to do so.';
    }
  }

  void _printCommand() {
    print(_color('\u001b[36m', '  ❯ dart run flutter_doctor . --verbose'));
    print('');
  }

  void _printProjectDetection(dynamic detector) {
    print('Detecting project...');
    
    final sm = detector.stateManagement as String;
    final parts1 = [
      '${_color("\u001b[32m", "✓ ")}Flutter ${_color("\u001b[1m", detector.flutterVersion as String)}',
      '${_color("\u001b[34m", "Dart ")}${_color("\u001b[1m", detector.dartVersion as String)}',
      if (sm.isNotEmpty) _color('\u001b[35m', sm),
    ];
    print('  ${parts1.join(_color("\u001b[90m", " · "))}');

    print('  ${_color("\u001b[32m", "✓ ")}Null safety enabled ${_color("\u001b[90m", "·")} ${detector.sourceFileCount} source files found');
    print('');
  }

  Future<void> _printHeader() async {
    print('Running analysis passes in parallel...');
    await _printSpinner();
    print(_color('\u001b[32m', '✓ Analysis complete'));
    print('');
    print(_color('\u001b[90m', '────────────────────────────────────────────────────────────────────────────'));
  }

  Future<void> _printSpinner() async {
    const spinners = ['⠋', '⠙', '⠹', '⠸', '⠼', '⠴', '⠦', '⠧', '⠇', '⠏'];
    final timer = Timer.periodic(const Duration(milliseconds: 100), (t) {
      final i = DateTime.now().millisecond ~/ 100 % 10;
      stderr
          .write('\r${spinners[i]} Lint pass       [████████████░░░░░░░░] 60%');
      stderr.flush();
    });
    await Future.delayed(const Duration(milliseconds: 2000));
    timer.cancel();
    stderr.write('\r${' ' * 60}\r');
    stderr.flush();
  }

  void _printLintDiagnostics(List diagnostics) {
    final lints = diagnostics
        .where((d) => d['type'] == 'ERR' || d['type'] == 'WARN')
        .toList();
    if (lints.isEmpty) return;

    print('');
    print(_color('\u001b[90;1m', 'LINT DIAGNOSTICS'));
    print('');
    
    for (final diag in lints.take(10)) {
      final type = diag['type'] as String;
      final rule = diag['rule'] as String;
      final location = diag['location'] as String;
      
      String tag;
      if (type == 'ERR') {
        tag = '\u001b[41;97m ERR \u001b[0m';
      } else {
        tag = '\u001b[43;30m WARN \u001b[0m'; 
      }
      
      final ruleColor = _color('\u001b[36m', rule);
      final locationColor = _color('\u001b[90m', location);
      
      int tagSpace = 5;
      int midSpace = 76 - tagSpace - 1 - rule.length - location.length;
      if (midSpace < 2) midSpace = 2;

      print(tag + '  ' + ruleColor + (' ' * midSpace) + locationColor);
      print('');
    }
    
    print(_color('\u001b[90m', '────────────────────────────────────────────────────────────────────────────'));
    print('');
  }

  void _printDeadCodeDiagnostics(List diagnostics) {
    final deads = diagnostics.where((d) => d['type'] == 'DEAD').toList();
    if (deads.isEmpty) return;

    print(_color('\u001b[90;1m', 'DEAD CODE'));
    print('');
    for (final diag in deads) {
      final subType = diag['subType'] as String? ?? 'UNKNOWN';
      final desc = diag['description'] as String;
      
      print('\u001b[44;97m DEAD \u001b[0m  ' +
          _color('\u001b[90m', subType.padRight(16).toUpperCase()) +
          _color('\u001b[37m', desc));
      print('');
    }
    print(_color('\u001b[90m', '────────────────────────────────────────────────────────────────────────────'));
    print('');
  }

  void _printHealthScore(
      int score, int errors, int warnings, int deadCount, int fileCount) {
    final filled = (score / 100 * 52).round();
    final empty = 52 - filled;
    final scoreColor = score >= 75
        ? '\u001b[32m'
        : score >= 50
            ? '\u001b[33m'
            : '\u001b[31m';
            
    final bar = _color(scoreColor, '━' * filled) + _color('\u001b[90m', '─' * empty);
    final boxColor = '\u001b[90m';
    
    final label = score >= 75
        ? 'Great'
        : score >= 50
            ? 'Needs work'
            : 'Critical';
            
    final scoreStr = score.toString();
    final statsStrRaw = '$errors errors  $warnings warnings  $deadCount dead code  $fileCount files scanned';
    final statsStr = '${_color('\u001b[1m\u001b[97m', errors.toString())} errors  ${_color('\u001b[1m\u001b[97m', warnings.toString())} warnings  ${_color('\u001b[1m\u001b[97m', deadCount.toString())} dead code  ${_color('\u001b[1m\u001b[97m', fileCount.toString())} files scanned';
    
    int textOffset = 13; 
    print(_color(boxColor, '╭───────────────────────────────────────────────────────────────────────────╮'));
    print(_color(boxColor, '│                                                                           │'));
    
    String l1Spaces = ' ' * (75 - textOffset - 12);
    print(_color(boxColor, '│') + _color(scoreColor, '  \u001b[1m\u001b[4m$scoreStr\u001b[24m\u001b[0m' + ' ' * (textOffset - 2 - scoreStr.length)) + _color(boxColor, 'HEALTH SCORE') + l1Spaces + _color(boxColor, '│'));
    
    String l2Spaces = ' ' * (75 - textOffset - 52);
    print(_color(boxColor, '│') + ' ' * textOffset + bar + l2Spaces + _color(boxColor, '│'));
    
    int l3Trail = 75 - textOffset - statsStrRaw.length;
    if (l3Trail < 0) l3Trail = 0;
    print(_color(boxColor, '│') + _color(scoreColor, '  $label' + ' ' * (textOffset - 2 - label.length)) + statsStr + (' ' * l3Trail) + _color(boxColor, '│'));
    
    print(_color(boxColor, '│                                                                           │'));
    print(_color(boxColor, '╰───────────────────────────────────────────────────────────────────────────╯'));
    print('');
  }

  void _printPriorityFixes(List diagnostics) {
    print('Top priority fixes:');
    final priorities =
        diagnostics.where((d) => d['type'] == 'ERR').take(3).toList();
    for (final diag in priorities) {
      print(
          '${_color('\u001b[31m', '→')} Fix ${_color('\u001b[36m', diag['rule'] as String)} — ${diag['description']}');
    }
    print('');
  }

  void _printFooter() {
    print(
        'Run ${_color('\u001b[36m', 'flutter_doctor . --fix')} to auto-fix with AI · ${_color('\u001b[36m', '--diff main')} for PR mode');
  }
}
